INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1000, 'bernie', 'Checkings', 1500);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1001, 'pawan', 'Savings', 2200);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1002, 'ben', 'Savings', 4506);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1003, 'poz', 'Checkings', 3206);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1004, 'george', 'Savings', 1236);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1005, 'anthony', 'Checkings', 9532);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1006, 'christopher', 'Checkings', 9622);
