INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(100, 'bernie', 'Checkings', 1500);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(101, 'pawan', 'Savings', 2200);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(102, 'ben', 'Savings', 4506);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(103, 'poz', 'Checkings', 3206);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(104, 'george', 'Savings', 1236);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(105, 'anthony', 'Checkings', 9532);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(106, 'christopher', 'Checkings', 9622);
