INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(1, 'bernie', 'Checkings', 1500);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(2, 'pawan', 'Savings', 2200);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(3, 'ben', 'Savings', 4506);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(4, 'poz', 'Checkings', 3206);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(5, 'george', 'Savings', 1236);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(6, 'anthony', 'Checkings', 9532);
INSERT INTO ACCOUNT (ID, USERNAME, ACCOUNT_TYPE, BALANCE) VALUES(7, 'christopher', 'Checkings', 9622);
